repos:
  - repo: local
    hooks:
      - id: commitizen-check
        name: Convention Commits (commit-msg)
        entry: python -m commitizen check --commit-msg-file
        language: system
        stages: [commit-msg]